# Generated by Django 5.2.7 on 2025-11-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_member_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['create']},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['create'], name='chat_messag_create_9c3b31_idx'),
        ),
    ]
