# Generated by Django 5.2.7 on 2025-11-06 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_member_chat_alter_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(related_name='joined_groups', through='chat.Member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='chat_groups',
            field=models.ManyToManyField(through='chat.Member', to='chat.chatgroup'),
        ),
    ]
